### ISSUE TITLE
Not using Gpu ?

### ISSUE THREAD

**Issue by Avinash424a** [sczhou/ProPainter#47]
cpu usage at 80% and 0 for gpu , 1.2 gb vram usage while running the inference painter.py , takes about 20-25 minutes for a 1 second video at 720p

**Comment by oranbox** [comment]
the same problem. Maybe the right version of CUDA or 4090 is not working

**Comment by thibaudart** [comment]
Same issue, I fix it with:

pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by thibaudart** [comment]
I fixed it with:

pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

**Comment by H-Dempsey** [comment]
I fixed the same issue by downgrading my version of python from 3.10 to 3.8.

**Comment by teidenzero** [comment]
> I fixed it with:
> 
> pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

This works for me, thank you! Can I ask you what was your thought process in order to come up with this solution?
